# Generated by Django 4.0.4 on 2022-05-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quality',
            new_name='quantity',
        ),
    ]
