name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  SECRET_KEY: Monday
  DATABASE_URL: postgres://cssanajdrcdehg:4815a269b84a54fceba02dc999e654b84883348aa42f2994be791d332e765aaf@ec2-3-234-131-8.compute-1.amazonaws.com:5432/d9cpo8nnu3uc3l

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
